DROP TABLE IF EXISTS Bitcoin;
CREATE TABLE Bitcoin (
    序號 INT AUTO_INCREMENT PRIMARY KEY,
    幣別名稱 VARCHAR(20) NOT NULL,
    幣別 VARCHAR(10) NOT NULL,
    匯率 VARCHAR(20) NOT NULL,
    說明 VARCHAR(100) NOT NULL,
    浮動利率 VARCHAR(30) NOT NULL,
    更新時間 VARCHAR(30) NOT NULL
);
